### ISSUE TITLE
[QUESTION] ¿Podemos crear un paquete en https://pypi.python.org/pypi?

### ISSUE THREAD

**Issue by moylop260** [apple314159/panama-dv#2]
Tu algoritmo es muy bueno, y sería genial poderlo tener disponible en
https://pypi.python.org/pypi
Para poder instalarlo desde cualquier computadora con:
`pip install panama-dv`

La pregunta es, si tú tienes algún problema de que registremos esta aplicación con nuestro usuario o prefieres hacerlo tú.

De antemano, gracias por tus esfuerzos publicados.

**Comment by apple314159** [comment]
Si, lo podes poner en pypi. Yo no tengo tiempo ahora para hacer eso.

Estoy curioso: para que lo vas a usar?

Yo estoy en David y estoy buscando programadores...

2015-09-01 18:22 GMT-05:00 moylop260 <notifications@github.com>:

**Comment by moylop260** [comment]
@oscarolar
Can you help us with this issue?

**Comment by moylop260** [comment]
@apple314159 
Thank for reply

We will create a new PR

**Comment by apple314159** [comment]
At this time I'm quite busy. I don't see much need to put it in Pypi as
this is very country specific
Why not just include it in your project?

**Comment by oscarolar** [comment]
sure, working on it @moylop260

**Comment by apple314159** [comment]
You don't have the right to change the license on my code! please update the pypi entry with the Apache license that I released the code with.
