### ISSUE TITLE
RUC Validation

### ISSUE THREAD

**Issue by plribeiro3000** [apple314159/panama-dv#7]
I've like to know where did you get the validation logic you've used here.

I need to port this to ruby but i need to check an official documentation if possible.

Thanks!

**Comment by apple314159** [comment]
The README has a broken link. A change of government removed many links and I don't know where they put them. I had a local copy but I no longer have access to it. It must be in a backup somewhere.

**Comment by apple314159** [comment]
A quick google search has found a couple of non-official links:

- https://www.academia.edu/25176178/ALGORITMO_PARA_EL_CALCULO_DEL_DIGITO_VERIFICADOR_DE_LA_RUC_Y_RECIBO
- https://www.scribd.com/document/412279635/Calculo-Digito-Verificador-RUC#

**Comment by plribeiro3000** [comment]
Awesome. Thank you @apple314159 

I was looking for an official link to use but those shall be a good start!
